[phases.setup]
nixPkgs = ["python3", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  # ⬇️ Run tests right after installing dependencies
  ". /opt/venv/bin/activate && pytest tests/ --maxfail=5 --disable-warnings"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port 8000"
